### ISSUE TITLE
form-select

### ISSUE THREAD

**Issue by Leeuwenkasteel** [tanthammar/tall-forms#113]
Hello,
I have make a fresh installation (with jetstream/livewire auth) in laravel and install your package but after npm run dev i got the follow error:

```
ERROR in ./resources/css/app.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
SyntaxError

<css input> You cannot `@apply` the `form-select` utility here because it creates a circular dependency.
    at processResult (C:\xampp\htdocs\test\node_modules\webpack\lib\NormalModule.js:753:19)
    at C:\xampp\htdocs\test\node_modules\webpack\lib\NormalModule.js:855:5
    at C:\xampp\htdocs\test\node_modules\loader-runner\lib\LoaderRunner.js:399:11
    at C:\xampp\htdocs\test\node_modules\loader-runner\lib\LoaderRunner.js:251:18
    at context.callback (C:\xampp\htdocs\test\node_modules\loader-runner\lib\LoaderRunner.js:124:13)
    at Object.loader (C:\xampp\htdocs\test\node_modules\postcss-loader\dist\index.js:140:7)

1 ERROR in child compilations (Use 'stats.children: true' resp. '--stats-children' for more details)
webpack compiled with 2 errors
```

**Environment:**
 - Tall-forms version:  "^8.2",
 - Livewire version: "^2.10"
 - Laravel version: "^9.2"

**Comment by gottaloveit** [comment]
I get the same thing

**Comment by emmadesilva** [comment]
Same here. Also using Jetstream (Livewire stack).

Fixed by replacing
```css
.form-multiselect {
    @apply form-select my-1 w-full shadow px-0 divide-y
}
```

with
```css
.form-multiselect {
    @apply focus:ring-gray-400 focus:border-gray-400 focus:shadow-md border-gray-300 rounded my-1 w-full shadow px-0 divide-y
}
```

on line 44 in resources\css\tall-theme.css

**Comment by tanthammar** [comment]
@caendesilva Thank you for suggesting a solution. Fixed in latest release.
