### ISSUE TITLE
npm run prod fails

### ISSUE THREAD

**Issue by slackerzz** [tanthammar/tall-forms#55]
**Describe the bug**
I've created a fresh installation of Laravel with Sail, added Livewire, Breeze and this amazing package.

I've followed the [Artisan Install](https://github.com/tanthammar/tall-forms/wiki/Artisan-Install) guide and tried to compile static assets.
- `npm run dev` works as expected
- `npm run prod` fails with errors

```
➜ vendor/bin/sail npm run prod

> prod
> npm run production


> production
> cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --config=node_modules/laravel-mix/setup/webpack.config.js


 ERROR  Failed to compile with 2 errors  

 error  in ./resources/css/app.css

Module build failed (from ./node_modules/css-loader/index.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
TypeError: Cannot read property 'filter' of undefined
    at n (/var/www/html/node_modules/@fullhuman/postcss-purgecss/lib/postcss-purgecss.js:1:509)
    at /var/www/html/node_modules/@fullhuman/postcss-purgecss/lib/postcss-purgecss.js:1:1513
    at LazyResult.run (/var/www/html/node_modules/postcss/lib/lazy-result.js:288:14)
    at LazyResult.asyncTick (/var/www/html/node_modules/postcss/lib/lazy-result.js:212:26)
    at LazyResult.asyncTick (/var/www/html/node_modules/postcss/lib/lazy-result.js:225:14)
    at LazyResult.asyncTick (/var/www/html/node_modules/postcss/lib/lazy-result.js:225:14)
    at LazyResult.asyncTick (/var/www/html/node_modules/postcss/lib/lazy-result.js:225:14)
    at LazyResult.asyncTick (/var/www/html/node_modules/postcss/lib/lazy-result.js:225:14)
    at LazyResult.asyncTick (/var/www/html/node_modules/postcss/lib/lazy-result.js:225:14)
    at LazyResult.asyncTick (/var/www/html/node_modules/postcss/lib/lazy-result.js:225:14)
    at LazyResult.asyncTick (/var/www/html/node_modules/postcss/lib/lazy-result.js:225:14)
    at LazyResult.asyncTick (/var/www/html/node_modules/postcss/lib/lazy-result.js:225:14)
    at LazyResult.asyncTick (/var/www/html/node_modules/postcss/lib/lazy-result.js:225:14)
    at LazyResult.asyncTick (/var/www/html/node_modules/postcss/lib/lazy-result.js:225:14)
    at /var/www/html/node_modules/postcss/lib/lazy-result.js:254:14
    at new Promise (<anonymous>)
    at LazyResult.async (/var/www/html/node_modules/postcss/lib/lazy-result.js:250:23)
    at LazyResult.then (/var/www/html/node_modules/postcss/lib/lazy-result.js:131:17)
    at LazyResult.asyncTick (/var/www/html/node_modules/postcss/lib/lazy-result.js:216:17)
    at LazyResult.asyncTick (/var/www/html/node_modules/postcss/lib/lazy-result.js:225:14)
    at LazyResult.asyncTick (/var/www/html/node_modules/postcss/lib/lazy-result.js:225:14)
    at /var/www/html/node_modules/postcss/lib/lazy-result.js:217:17
    at /var/www/html/node_modules/webpack/lib/NormalModule.js:316:20
    at /var/www/html/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /var/www/html/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/var/www/html/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /var/www/html/node_modules/postcss-loader/src/index.js:208:9

 error  in ./resources/css/app.css

Module build failed (from ./node_modules/postcss-loader/src/index.js):
TypeError: Cannot read property 'filter' of undefined
    at n (/var/www/html/node_modules/@fullhuman/postcss-purgecss/lib/postcss-purgecss.js:1:509)
    at /var/www/html/node_modules/@fullhuman/postcss-purgecss/lib/postcss-purgecss.js:1:1513
    at LazyResult.run (/var/www/html/node_modules/postcss/lib/lazy-result.js:288:14)
    at LazyResult.asyncTick (/var/www/html/node_modules/postcss/lib/lazy-result.js:212:26)
    at LazyResult.asyncTick (/var/www/html/node_modules/postcss/lib/lazy-result.js:225:14)
    at LazyResult.asyncTick (/var/www/html/node_modules/postcss/lib/lazy-result.js:225:14)
    at LazyResult.asyncTick (/var/www/html/node_modules/postcss/lib/lazy-result.js:225:14)
    at LazyResult.asyncTick (/var/www/html/node_modules/postcss/lib/lazy-result.js:225:14)
    at LazyResult.asyncTick (/var/www/html/node_modules/postcss/lib/lazy-result.js:225:14)
    at LazyResult.asyncTick (/var/www/html/node_modules/postcss/lib/lazy-result.js:225:14)
    at LazyResult.asyncTick (/var/www/html/node_modules/postcss/lib/lazy-result.js:225:14)
    at LazyResult.asyncTick (/var/www/html/node_modules/postcss/lib/lazy-result.js:225:14)
    at LazyResult.asyncTick (/var/www/html/node_modules/postcss/lib/lazy-result.js:225:14)
    at LazyResult.asyncTick (/var/www/html/node_modules/postcss/lib/lazy-result.js:225:14)
    at /var/www/html/node_modules/postcss/lib/lazy-result.js:254:14
    at new Promise (<anonymous>)
    at LazyResult.async (/var/www/html/node_modules/postcss/lib/lazy-result.js:250:23)
    at LazyResult.then (/var/www/html/node_modules/postcss/lib/lazy-result.js:131:17)
    at LazyResult.asyncTick (/var/www/html/node_modules/postcss/lib/lazy-result.js:216:17)
    at LazyResult.asyncTick (/var/www/html/node_modules/postcss/lib/lazy-result.js:225:14)
    at LazyResult.asyncTick (/var/www/html/node_modules/postcss/lib/lazy-result.js:225:14)
    at /var/www/html/node_modules/postcss/lib/lazy-result.js:217:17

 @ ./resources/css/app.css 2:14-142

 2 assets

ERROR in ./resources/css/app.css
Module build failed (from ./node_modules/css-loader/index.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
TypeError: Cannot read property 'filter' of undefined
    at n (/var/www/html/node_modules/@fullhuman/postcss-purgecss/lib/postcss-purgecss.js:1:509)
    at /var/www/html/node_modules/@fullhuman/postcss-purgecss/lib/postcss-purgecss.js:1:1513
    at LazyResult.run (/var/www/html/node_modules/postcss/lib/lazy-result.js:288:14)
    at LazyResult.asyncTick (/var/www/html/node_modules/postcss/lib/lazy-result.js:212:26)
    at LazyResult.asyncTick (/var/www/html/node_modules/postcss/lib/lazy-result.js:225:14)
    at LazyResult.asyncTick (/var/www/html/node_modules/postcss/lib/lazy-result.js:225:14)
    at LazyResult.asyncTick (/var/www/html/node_modules/postcss/lib/lazy-result.js:225:14)
    at LazyResult.asyncTick (/var/www/html/node_modules/postcss/lib/lazy-result.js:225:14)
    at LazyResult.asyncTick (/var/www/html/node_modules/postcss/lib/lazy-result.js:225:14)
    at LazyResult.asyncTick (/var/www/html/node_modules/postcss/lib/lazy-result.js:225:14)
    at LazyResult.asyncTick (/var/www/html/node_modules/postcss/lib/lazy-result.js:225:14)
    at LazyResult.asyncTick (/var/www/html/node_modules/postcss/lib/lazy-result.js:225:14)
    at LazyResult.asyncTick (/var/www/html/node_modules/postcss/lib/lazy-result.js:225:14)
    at LazyResult.asyncTick (/var/www/html/node_modules/postcss/lib/lazy-result.js:225:14)
    at /var/www/html/node_modules/postcss/lib/lazy-result.js:254:14
    at new Promise (<anonymous>)
    at LazyResult.async (/var/www/html/node_modules/postcss/lib/lazy-result.js:250:23)
    at LazyResult.then (/var/www/html/node_modules/postcss/lib/lazy-result.js:131:17)
    at LazyResult.asyncTick (/var/www/html/node_modules/postcss/lib/lazy-result.js:216:17)
    at LazyResult.asyncTick (/var/www/html/node_modules/postcss/lib/lazy-result.js:225:14)
    at LazyResult.asyncTick (/var/www/html/node_modules/postcss/lib/lazy-result.js:225:14)
    at /var/www/html/node_modules/postcss/lib/lazy-result.js:217:17
    at /var/www/html/node_modules/webpack/lib/NormalModule.js:316:20
    at /var/www/html/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /var/www/html/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/var/www/html/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /var/www/html/node_modules/postcss-loader/src/index.js:208:9
  @ ./resources/css/app.css

ERROR in ./resources/css/app.css (./node_modules/css-loader??ref--5-2!./node_modules/postcss-loader/src??postcss0!./resources/css/app.css)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
TypeError: Cannot read property 'filter' of undefined
    at n (/var/www/html/node_modules/@fullhuman/postcss-purgecss/lib/postcss-purgecss.js:1:509)
    at /var/www/html/node_modules/@fullhuman/postcss-purgecss/lib/postcss-purgecss.js:1:1513
    at LazyResult.run (/var/www/html/node_modules/postcss/lib/lazy-result.js:288:14)
    at LazyResult.asyncTick (/var/www/html/node_modules/postcss/lib/lazy-result.js:212:26)
    at LazyResult.asyncTick (/var/www/html/node_modules/postcss/lib/lazy-result.js:225:14)
    at LazyResult.asyncTick (/var/www/html/node_modules/postcss/lib/lazy-result.js:225:14)
    at LazyResult.asyncTick (/var/www/html/node_modules/postcss/lib/lazy-result.js:225:14)
    at LazyResult.asyncTick (/var/www/html/node_modules/postcss/lib/lazy-result.js:225:14)
    at LazyResult.asyncTick (/var/www/html/node_modules/postcss/lib/lazy-result.js:225:14)
    at LazyResult.asyncTick (/var/www/html/node_modules/postcss/lib/lazy-result.js:225:14)
    at LazyResult.asyncTick (/var/www/html/node_modules/postcss/lib/lazy-result.js:225:14)
    at LazyResult.asyncTick (/var/www/html/node_modules/postcss/lib/lazy-result.js:225:14)
    at LazyResult.asyncTick (/var/www/html/node_modules/postcss/lib/lazy-result.js:225:14)
    at LazyResult.asyncTick (/var/www/html/node_modules/postcss/lib/lazy-result.js:225:14)
    at /var/www/html/node_modules/postcss/lib/lazy-result.js:254:14
    at new Promise (<anonymous>)
    at LazyResult.async (/var/www/html/node_modules/postcss/lib/lazy-result.js:250:23)
    at LazyResult.then (/var/www/html/node_modules/postcss/lib/lazy-result.js:131:17)
    at LazyResult.asyncTick (/var/www/html/node_modules/postcss/lib/lazy-result.js:216:17)
    at LazyResult.asyncTick (/var/www/html/node_modules/postcss/lib/lazy-result.js:225:14)
    at LazyResult.asyncTick (/var/www/html/node_modules/postcss/lib/lazy-result.js:225:14)
    at /var/www/html/node_modules/postcss/lib/lazy-result.js:217:17
 @ ./resources/css/app.css 2:14-142
npm ERR! code 2
npm ERR! path /var/www/html
npm ERR! command failed
npm ERR! command sh -c cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --config=node_modules/laravel-mix/setup/webpack.config.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sail/.npm/_logs/2020-12-27T10_14_06_322Z-debug.log
npm ERR! code 2
npm ERR! path /var/www/html
npm ERR! command failed
npm ERR! command sh -c npm run production

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sail/.npm/_logs/2020-12-27T10_14_06_339Z-debug.log
```

**Environment:**
 - Tall-forms version: 7.3.2
 - Livewire version: 2.3.5
 - Laravel version: 8.20.1
 - $wrapWithLayout true/false: true
    - if true, Are you using your own wrapper component or the default one?: The default one
 - Have you published the view files?: Yes
 - Have you published, and edited the config file?: Yes and No
 - Laravel Breeze: 1.0.1
 - TailwindCSS: 2.0.2

The problem seems to be in the `tailwind.config.js` file from this package, in the purge step, becouse the file is missing the `content` field in the `purge` config object

**Comment by tanthammar** [comment]
@slackerzz Thank you for reporting.

I've been on this all day.

Think there is something with the new Tailwind 2.x preset.

I think I found the culprit, but I need to do some more tests. Will get back to you shortly.

**Comment by tanthammar** [comment]
@slackerzz 

Can you help me confirm that this works in your installation before I publish a release to solve this issue.

Please upgrade your `tailwind.config.js` to this:
```js
// const defaultTheme = require('tailwindcss/defaultTheme');

module.exports = {
    presets: [
        // the preset merges, fonts, variants, plugins, colors and purge content
        require('./vendor/tanthammar/tall-forms/resources/stubs/tailwindcss/2.0/tall-forms-preset.js'),
    ],
    theme: {
        extend: {}
    },
    variants: {},
    plugins: [],
};
```

And manually change the source file for the preset. 

`vendor/tanthammar/tall-forms/resources/stubs/tailwindcss/2.0/tall-forms-preset.js`

```js
const defaultTheme = require('tailwindcss/defaultTheme');

module.exports = {
    purge: {
        content: [
            './app/**/*.php',
            //if Jetstream
            './vendor/laravel/jetstream/**/*.blade.php',
            //if Jetstream or Breeze
            './storage/framework/views/*.php',
            //endif Jetstream or Breeze
            // Tall-forms start
            './config/tall-forms.php',
            './vendor/tanthammar/tall-forms/**/*.php',
            './vendor/tanthammar/tall-forms-sponsors/**/*.php',
            // Tall-forms end
            // Add the file formats applicable to your project
            './resources/**/*.html',
            './resources/**/*.js',
            './resources/**/*.jsx',
            './resources/**/*.ts',
            './resources/**/*.tsx',
            './resources/**/*.php',
            './resources/**/*.vue',
            './resources/**/*.twig',
        ],
        options: {
            defaultExtractor: (content) => content.match(/[^<>"'`\s]*[^<>"'`\s:]/g) || [],
            safeList: [/-active$/, /-enter$/, /-leave-to$/, /show$/],
        },
    },
    
    theme: {
        extend: {
            fontFamily: {
                sans: ['Nunito', ...defaultTheme.fontFamily.sans],
            },
            colors: {
                teal: {
                    100: '#e6fffa',
                    200: '#b2f5ea',
                    300: '#81e6d9',
                    400: '#4fd1c5',
                    500: '#38b2ac',
                    600: '#319795',
                    700: '#2c7a7b',
                    800: '#285e61',
                    900: '#234e52',
                },
            },
        },
    },

    variants: {
        extend: {
            opacity: ['responsive', 'hover', 'focus', 'disabled'],
        },
    },

    plugins: [
        require('@tailwindcss/typography'),
        require('@tailwindcss/forms'),
        require('@tailwindcss/aspect-ratio'),
    ],
};
```

Please report back when you have tested.

**Comment by tanthammar** [comment]
BTW, I assume you're on Tailwind 2.x? (Because you're using Breeze)

**Comment by tanthammar** [comment]
@slackerzz if you haven't made any changes, you can install the new release and run the
 `php artisan make:tall-forms-installation` again.
